include: package:very_good_analysis/analysis_options.3.0.1.yaml
linter:
  rules:
    public_member_api_docs: false
    always_use_package_imports: false
    lines_longer_than_80_chars: false
    unnecessary_lambdas: false
    flutter_style_todos: false

analyzer:
  exclude:
    - "lib/generated/"
    - "**/*.g.dart"
    - "**/*.mocks.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore